var subjectNames = {
    "acc": "Accounting",
    "adm": "Administration & IT",
    "apmt": "Applications of Mathematics",
    "art": "Art & Design",
    "bio": "Biology",
    "bus": "Business Management",
    "can": "Cantonese",
    "car": "Care",
    "chem": "Chemistry",
    "chd": "Childcare & Development",
    "cla": "Classical Studies",
    "cs": "Computing Science",
    "cre": "Cruinn eolas",
    "dan": "Dance",
    "dnm": "Design & Manufacture",
    "dra": "Drama",
    "esol": "ESOL",
    "eac": "Eachdraidh",
    "eco": "Economics",
    "egs": "Engineering Science",
    "eng": "English",
    "env": "Environmental Science",
    "fas": "Fashion & Textile Technology",
    "fren": "French",
    "gae": "Gaelic (Learners)",
    "geo": "Geography",
    "ger": "German",
    "grc": "Graphic Communication",
    "gai": "Gàidhlig",
    "hea": "Health & Food Technology",
    "his": "History",
    "hum": "Human Biology",
    "ita": "Italian",
    "lat": "Latin",
    "mans": "Mandarin Simplified",
    "mant": "Mandarin Traditional",
    "math": "Mathematics",
    "mata": "Matamataig",
    "matm": "Mathematics of Mechanics",
    "med": "Media",
    "mod": "Modern Studies",
    "mus": "Music",
    "mtch": "Music Technology",
    "nua": "Nuadh eolas",
    "phi": "Philosophy",
    "pho": "Photography",
    "pe": "Physical Education",
    "phys": "Physics",
    "pol": "Politics",
    "pcc": "Practical Cake Craft",
    "prc": "Practical Cookery",
    "pre": "Practical Electronics",
    "prm": "Practical Metalworking",
    "prw": "Practical Woodworking",
    "psy": "Psychology",
    "rmps": "Religious, Moral and Philosophical Studies",
    "soc": "Sociology",
    "spa": "Spanish",
    "stat": "Statistics",
    "urdu": "Urdu",
}

var levelNames = {
    "n5": "National 5",
    "nh": "Higher",
    "ah": "Advanced Higher"
}

var paperNames = {
    "all": "All",
    "qp": "Question Paper",
    // Sciences & Mathematics
    "p1": "Paper 1",
    "p2": "Paper 2",
    "s1": "Section 1",
    "s2": "Section 2",
    // English
    "cr": "Critical Reading",
    "ru": "RUAE",
    // Modern Languages
    "re": "Reading",
    "li": "Listening",
    "dw": "Directed Writing",
    "wr": "Writing",
    // Geography
    "gg": "Global Issues and Geographical Skills",
    "ph": "Physical and Human Environments",
    // History
    "bw": "British, European and World-History",
    "sh":"Scottish History",
    // Media
    "am": "Analysis of Media Content",
    "rm": "The Role of Media",
}